version: '2'

services:

  req:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-work:1.0.0
    container_name: req
    volumes:
      - .:/go/src/req
    entrypoint: tail -f /dev/null
